# Generated by Django 5.0.3 on 2024-03-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoOtika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hiz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ivme', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rotasyon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.TimeField()),
                ('ilac', models.IntegerField()),
                ('batarya', models.IntegerField()),
                ('akim', models.DecimalField(decimal_places=2, max_digits=10)),
                ('derece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imha_bitkiler', models.IntegerField()),
                ('asilan_engeller', models.IntegerField()),
                ('durdur', models.BooleanField()),
                ('bitki_resim', models.ImageField(upload_to='static/images')),
                ('x_ekseni', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y_ekseni', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
